<table>
    <thead>
        <tr>
            <th>Available fields</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Checkbox</td>
        </tr>
        <tr>
            <td>Code</td>
        </tr>
        <tr>
            <td>Color</td>
        </tr>
        <tr>
            <td>Date</td>
        </tr>
        <tr>
            <td>DateRange</td>
        </tr>
        <tr>
            <td>Email</td>
        </tr>
        <tr>
            <td>Enum</td>
        </tr>
        <tr>
            <td>File</td>
        </tr>
        <tr>
            <td>Hidden</td>
        </tr>
        <tr>
            <td>HiddenIds</td>
        </tr>
        <tr>
            <td>ID</td>
        </tr>
        <tr>
            <td>Image</td>
        </tr>
        <tr>
            <td>Json</td>
        </tr>
        <tr>
            <td>Markdown</td>
        </tr>
        <tr>
            <td>Number</td>
        </tr>
        <tr>
            <td>Password</td>
        </tr>
        <tr>
            <td>PasswordRepeat</td>
        </tr>
        <tr>
            <td>Phone</td>
        </tr>
        <tr>
            <td>Position</td>
        </tr>
        <tr>
            <td>Preview</td>
        </tr>
        <tr>
            <td>Range</td>
        </tr>
        <tr>
            <td>RangeSlider</td>
        </tr>
        <tr>
            <td>Select</td>
        </tr>
        <tr>
            <td>Slug</td>
        </tr>
        <tr>
            <td>Switcher</td>
        </tr>
        <tr>
            <td>Template</td>
        </tr>
        <tr>
            <td>Text</td>
        </tr>
        <tr>
            <td>Textarea</td>
        </tr>
        <tr>
            <td>TinyMce</td>
        </tr>
        <tr>
            <td>Url</td>
        </tr>

    </tbody>
</table>
