<table>
    <thead>
    <tr>
        <th>Available types</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>id</td>
    </tr>
    <tr>
        <td>bigInteger</td>
    </tr>
    <tr>
        <td>mediumInteger</td>
    </tr>
    <tr>
        <td>integer</td>
    </tr>
    <tr>
        <td>smallInteger</td>
    </tr>
    <tr>
        <td>tinyInteger</td>
    </tr>
    <tr>
        <td>unsignedBigInteger</td>
    </tr>
    <tr>
        <td>unsignedMediumInteger</td>
    </tr>
    <tr>
        <td>unsignedInteger</td>
    </tr>
    <tr>
        <td>unsignedSmallInteger</td>
    </tr>
    <tr>
        <td>unsignedTinyInteger</td>
    </tr>
    <tr>
        <td>decimal</td>
    </tr>
    <tr>
        <td>boolean</td>
    </tr>
    <tr>
        <td>double</td>
    </tr>
    <tr>
        <td>float</td>
    </tr>
    <tr>
        <td>string</td>
    </tr>
    <tr>
        <td>char</td>
    </tr>
    <tr>
        <td>json</td>
    </tr>
    <tr>
        <td>jsonb</td>
    </tr>
    <tr>
        <td>text</td>
    </tr>
    <tr>
        <td>longText</td>
    </tr>
    <tr>
        <td>mediumText</td>
    </tr>
    <tr>
        <td>tinyText</td>
    </tr>
    <tr>
        <td>uuid</td>
    </tr>
    <tr>
        <td>timestamp</td>
    </tr>
    <tr>
        <td>dateTime</td>
    </tr>
    <tr>
        <td>year</td>
    </tr>
    <tr>
        <td>date</td>
    </tr>
    <tr>
        <td>time</td>
    </tr>
    <tr>
        <td>BelongsTo</td>
    </tr>
    <tr>
        <td>BelongsToMany</td>
    </tr>
    <tr>
        <td>HasOne</td>
    </tr>
    <tr>
        <td>HasMany</td>
    </tr>
    </tbody>
</table>