<?php
?>

<table class="table">
    <thead>
        <tr>
            <th>Available types</th>
            <th>Available fields</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>id</td>
            <td>Checkbox</td>
        </tr>
        <tr>
            <td>bigInteger</td>
            <td>Code</td>
        </tr>
        <tr>
            <td>mediumInteger</td>
            <td>Color</td>
        </tr>
        <tr>
            <td>integer</td>
            <td>Date</td>
        </tr>
        <tr>
            <td>smallInteger</td>
            <td>DateRange</td>
        </tr>
        <tr>
            <td>tinyInteger</td>
            <td>Email</td>
        </tr>
        <tr>
            <td>unsignedBigInteger</td>
            <td>Enum</td>
        </tr>
        <tr>
            <td>unsignedMediumInteger</td>
            <td>File</td>
        </tr>
        <tr>
            <td>unsignedInteger</td>
            <td>Hidden</td>
        </tr>
        <tr>
            <td>unsignedSmallInteger</td>
            <td>HiddenIds</td>
        </tr>
        <tr>
            <td>unsignedTinyInteger</td>
            <td>ID</td>
        </tr>
        <tr>
            <td>decimal</td>
            <td>Image</td>
        </tr>
        <tr>
            <td>boolean</td>
            <td>Json</td>
        </tr>
        <tr>
            <td>double</td>
            <td>Markdown</td>
        </tr>
        <tr>
            <td>float</td>
            <td>Number</td>
        </tr>
        <tr>
            <td>string</td>
            <td>Password</td>
        </tr>
        <tr>
            <td>char</td>
            <td>PasswordRepeat</td>
        </tr>
        <tr>
            <td>json</td>
            <td>Phone</td>
        </tr>
        <tr>
            <td>jsonb</td>
            <td>Position</td>
        </tr>
        <tr>
            <td>text</td>
            <td>Preview</td>
        </tr>
        <tr>
            <td>longText</td>
            <td>Range</td>
        </tr>
        <tr>
            <td>mediumText</td>
            <td>RangeSlider</td>
        </tr>
        <tr>
            <td>tinyText</td>
            <td>Select</td>
        </tr>
        <tr>
            <td>uuid</td>
            <td>Slug</td>
        </tr>
        <tr>
            <td>timestamp</td>
            <td>Switcher</td>
        </tr>
        <tr>
            <td>dateTime</td>
            <td>Template</td>
        </tr>
        <tr>
            <td>year</td>
            <td>Text</td>
        </tr>
        <tr>
            <td>date</td>
            <td>Textarea</td>
        </tr>
        <tr>
            <td>time</td>
            <td>TinyMce</td>
        </tr>
        <tr>
            <td>BelongsTo</td>
            <td>Url</td>
        </tr>
        <tr>
            <td>BelongsToMany</td>
            <td></td>
        </tr>
        <tr>
            <td>HasOne</td>
            <td></td>
        </tr>
        <tr>
            <td>HasMany</td>
            <td></td>
        </tr>
    </tbody>
</table>
